### ISSUE TITLE
Add pass range indicator

### ISSUE THREAD

**Issue by christophercarney** [BrothersStudio/tailpipe_seven#43]
Possibly make the pass range highlight the tiles in green? It's hard to plan out your turn without it

**Comment by pwcarney** [comment]
How would this look? I don't want a permanent 3 block range appearing around the ball player, I think?

**Comment by christophercarney** [comment]
when you select move it shows you the movement, same thing for pass, when you select pass you see the range

**Comment by pwcarney** [comment]
Oh, that's it? Okay, I can do that

**Comment by christophercarney** [comment]
Just so at the beginning of the turn the player can see the range of both actions off the bat before making any decisions

**Comment by pwcarney** [comment]
Okay maybe I'm not clear, then. Here's what I'm picturing:

Cursor selects player: menu appears and default highlights over Pass 
When Pass is highlighted in the command menu and available (AKA the player has the ball and hasn't attacked this turn): squares in range of pass turn green
When Pass menu item is selected, nothing changes, the green turns off and all we see is the X number of red selected potential pass targets

Is that what you had in mind?

**Comment by christophercarney** [comment]
Yeah that's perfect.

I that case i think movement should behave the same way. Currently you need to click on move to see how far you can move, it should appear on hover

**Comment by pwcarney** [comment]
Makes sense
