### ISSUE TITLE
If the player can still perform and action (move, pass, push) after first completes, leave action menu up

### ISSUE THREAD

**Issue by christophercarney** [BrothersStudio/tailpipe_seven#59]
I feel like a lot of players will try to play both moves in a row. So the action menu should stay up by default if there is another available action, saves the player the tedium of selecting the same character again

**Comment by pwcarney** [comment]
Okay, I buy that

**Comment by pwcarney** [comment]
This fix has revealed a new one (or rather, one that was hard-ish to do before but easy now)

#62
