### ISSUE TITLE
Player shouldn't be able to move to the square they are standing on.

### ISSUE THREAD

**Issue by christophercarney** [BrothersStudio/tailpipe_seven#60]
Sometimes i accidentally want to cancel but instead i'll move to the same square i'm standing on. This is frustrating on multiple levels. The square you're standing on shouldn't be highlighted and shouldn't be a valid movement position

**Comment by pwcarney** [comment]
Aww, that's only allowed because it makes some AI calculations easier, stop making me not be lazy. fine fine
