### ISSUE TITLE
How to handle "no more moves" possible

### ISSUE THREAD

**Issue by christophercarney** [BrothersStudio/tailpipe_seven#61]
Sometimes your player remains highlighted when they can't make any more moves (like when they move but they can technically still "push" and no enemies are around -- but I guess someone could push someone into their way?) Likewise I guess they could still catch/pass the ball.

It just feels a little awkward. But it's hard to calculate if the player can make any more moves and display the end turn dialogue I guess. What are your thoughts?

**Comment by pwcarney** [comment]
It is awkward. I've tried to fix this, but, like you said, someone can move into range at a later point. I think it's just as awkward to set them inactive and then "reactivate" them when the attack becomes valid. Because users will forget which players still have pushes and passes left. I don't think there's an elegant solution, per-se, but that's what the manual end turn is for.

**Comment by christophercarney** [comment]
Maybe little "status effect" icons at the bottom of each player's model (one for pass, move, push).

When the user has all three actions display nothing. When they take an action display the two they have left, if they push, etc remove it.

That's the most elegant situation I can think of, at least.

**Comment by christophercarney** [comment]
Or maybe when you hover over a player it displays the action icons they have remaining? If they took an action it'll be grayed out

**Comment by pwcarney** [comment]
Not really a fan of adding icons, just adds to player confusion I think

**Comment by pwcarney** [comment]
Especially if they're hovering over a player or something like they'd have to be, the field is already too busy. I think it's okay to just have the End Action menu. Most games like this do a similar thing.

**Comment by pwcarney** [comment]
As it is, if someone clicks on a "Still active" player with no available actions, they can hover over "push" and see the available push squares so I think it's pretty clear

**Comment by christophercarney** [comment]
Ok makes sense
