### ISSUE TITLE
Implement animated tile highlight

### ISSUE THREAD

**Issue by krcarney** [BrothersStudio/tailpipe_seven#72]
Use fancy tile highlighting for play to make it more noticeable who you are selecting, who you are passing to, etc.

**Comment by pwcarney** [comment]
That’s a good idea. Anything to help make things more clear. Maybe even on AI turns we need to be “highlighting” which player is going.

**Comment by krcarney** [comment]
I pushed a 2 frame tile highlighting animation a couple days ago. try that. I'm also going to make an arrow for pointing at the selected tile
